name: waveglow
channels:
	- httpsL//conda.anaconda.org/menpo
	- conda-forge
dependencies:
	- python==3.5.2
	- matplotlib==2.1.0
	- numpy==1.13.3
	- inflect==0.2.5
	- librosa==0.6.0
	- scipy==1.0.0
	- tensorboardX==1.1
	- Unidecode=1.0.22
	- pytorch==1.0
